### ISSUE TITLE
Output Mesh as obj or glb

### ISSUE THREAD

**Issue by sekkit** [NIRVANALAN/GaussianAnything#1]
Is it possible to export obj or glb with your point cloud format?

**Comment by NIRVANALAN** [comment]
Hi, thanks for your interest. Sure, the final result supports exporting a colored point cloud and TSDF mesh. I will update the code and publish the gradio demo soon which supports this. Will keep you updated.

**Comment by NIRVANALAN** [comment]
Hi, I have just updated the gradio demo code (for local GPU run). Please check the readme accordingly. The Hugging face version is still under debugging and will be posted soon.

**Comment by sekkit** [comment]
ok, but i find the mesh produced not as good as other papers, is there a problem with the point cloud conversion?

**Comment by NIRVANALAN** [comment]
Exactly, though 2DGS performs well on surface compared to 3DGS, the point to mesh conversion is still achieved by TSDF integration. I find that reducing the voxel_size in the integration leads to better mesh quality, but with a much larger mesh size. https://github.com/NIRVANALAN/GaussianAnything/blob/dd72e4235431a683d5cf4d868a7b19e9034c2b8d/nsr/lsgm/flow_matching_trainer.py#L1298

Also, using more views for mesh integration improves the quality (e.g., from 10 to 50), but this also leads to slower inference time. Feel free to tune the parameter if needed.
https://github.com/NIRVANALAN/GaussianAnything/blob/dd72e4235431a683d5cf4d868a7b19e9034c2b8d/nsr/lsgm/flow_matching_trainer.py#L1679
