### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by silence-tang** [NIRVANALAN/GaussianAnything#6]
Hi, may I ask how long does it take to finishing training on 8 A100 GPUs?

**Comment by NIRVANALAN** [comment]
Hi, for diffusion side usually 500K iteration already works well. DiT-L size transformer takes around 7 days to finalize (70~80K iterations per day). The two models (point cloud diffusion model and point cloud feature model) can be trained in parrallel.

For 3D VAE, the compute is roughly the same. A week shall be enough.
