### ISSUE TITLE
error occurred when running test-to-3D

### ISSUE THREAD

**Issue by yejr0229** [NIRVANALAN/GaussianAnything#7]
Hi, I use this command "bash shell_scripts/release/inference/t23d/stage1-t23d.sh" to run the text-to-3d, and get the following error, could you please tell me how to fix it? Thanks in advance!
Traceback (most recent call last):
  File "/apdcephfs_qy4/share_782420/yejr/GaussianAnything-main/scripts/vit_triplane_sit_sample.py", line 399, in <module>
    training_loop(args)
  File "/apdcephfs_qy4/share_782420/yejr/GaussianAnything-main/scripts/vit_triplane_sit_sample.py", line 285, in training_loop
    training_loop_class.eval_and_export(
  File "/opt/conda/envs/ga/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: FlowMatchingEngine_gs.eval_and_export() got an unexpected keyword argument 'unconditional_guidance_scale'

**Comment by yejr0229** [comment]
I have fixed these errors by adding the following two parameters:
![企业微信截图_17351900406616](https://github.com/user-attachments/assets/24841c10-213f-4798-947f-d472582ad616)
But now I get another torch.distributed error:
![image](https://github.com/user-attachments/assets/204e11c9-7325-4397-a342-9cf16bfc41f1)
And I use torch2.3.0+cu12.1 with cuda12.1:
![image](https://github.com/user-attachments/assets/e11a87e5-80e3-4814-806e-2761a60e88e3)

**Comment by yejr0229** [comment]
Thanks for replying, I have fixed it by installing torch2.10+cu118

**Comment by NIRVANALAN** [comment]
Glad to hear that.

**Comment by yejr0229** [comment]
Sorry to bother, but I encounter another error when running the stage-2:
![image](https://github.com/user-attachments/assets/54ce954a-5e73-4608-b725-ce8eeacdfa5c)
Could you please tell me how to fix this?
